# Write it!

Reek/DuplicateMethodCall:
  Description: 'Checks for repeated identical method calls within a single method definition.'
  Enabled: pending
  MaxCalls: 1
  AllowCalls: []
  VersionAdded: '<<next>>'

Reek/NilCheck:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '<<next>>'
