# Write it!

Reek/DuplicateMethodCall:
  Description: 'Checks for repeated identical method calls within a single method definition.'
  Enabled: pending
  MaxCalls: 1
  AllowCalls: []
  VersionAdded: '<<next>>'

Reek/NilCheck:
  Description: 'TODO: Write a description of the cop.'
  Enabled: pending
  VersionAdded: '<<next>>'

Reek/TooManyInstanceVariables:
  Description: 'Checks that a class has no more than a configurable number of instance variables.'
  Enabled: pending
  MaxInstanceVariables: 4
  VersionAdded: '<<next>>'
